#!/usr/bin/env bash
# Check if script is run as root
if [ "$EUID" -ne 0 ]
	then echo "Please run as root"
	exit
fi

# Append the necessary lines to /etc/hosts
echo '127.0.0.2 localhost' | tee -a /etc/hosts
echo '8.8.8.8 facebook.com' | tee -a /etc/hosts
